import mongoose from 'mongoose';
const { Schema, model } = mongoose;

const userSchema = new Schema({ name: String, email: { type: String, unique: true }, password: String, role: { type: String, enum: ['STUDENT', 'ADMIN', 'COMPANY'], default: 'STUDENT' }, active: { type: Boolean, default: true } }, { timestamps: true });
const studentSchema = new Schema({ user: { type: Schema.Types.ObjectId, ref: 'User', unique: true }, phone: String, course: String, branch: String, graduationYear: Number, cgpa: Number, tenthPercentage: Number, twelfthPercentage: Number, skills: [String], resumeUrl: String, projects: [String], certifications: [String] }, { timestamps: true });
const companySchema = new Schema({ name: String, logo: String, description: String, website: String, industry: String, approved: { type: Boolean, default: false }, active: { type: Boolean, default: true } }, { timestamps: true });
const driveSchema = new Schema({ company: { type: Schema.Types.ObjectId, ref: 'Company' }, jobTitle: String, jobDescription: String, packageLpa: Number, location: String, openings: Number, requiredSkills: [String], minCgpa: Number, minTenth: Number, minTwelfth: Number, eligibleBranches: [String], eligibleYears: [Number], applicationStart: Date, applicationDeadline: Date, driveDate: Date, status: { type: String, enum: ['UPCOMING', 'OPEN', 'CLOSED', 'COMPLETED', 'CANCELLED'], default: 'UPCOMING' } }, { timestamps: true });
const roundSchema = new Schema({ drive: { type: Schema.Types.ObjectId, ref: 'Drive' }, name: String, type: { type: String, enum: ['APTITUDE', 'CODING', 'TECHNICAL_TEST', 'TECHNICAL_INTERVIEW', 'HR_INTERVIEW', 'GROUP_DISCUSSION', 'OTHER'] }, date: Date, startTime: String, endTime: String, location: String, meetingLink: String, instructions: String, status: { type: String, default: 'SCHEDULED' } }, { timestamps: true });
const applicationSchema = new Schema({ student: { type: Schema.Types.ObjectId, ref: 'Student' }, drive: { type: Schema.Types.ObjectId, ref: 'Drive' }, status: { type: String, enum: ['APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'SELECTED', 'WITHDRAWN'], default: 'APPLIED' }, currentStage: { type: String, default: 'Application submitted' }, rejectionReason: String, finalDate: Date, roundResults: [{ round: { type: Schema.Types.ObjectId, ref: 'Round' }, status: String, note: String, updatedAt: Date }] }, { timestamps: true });
applicationSchema.index({ student: 1, drive: 1 }, { unique: true });
const notificationSchema = new Schema({ recipient: { type: Schema.Types.ObjectId, ref: 'User' }, title: String, body: String, read: { type: Boolean, default: false }, kind: String }, { timestamps: true });
export const User = model('User', userSchema); export const Student = model('Student', studentSchema); export const Company = model('Company', companySchema); export const Drive = model('Drive', driveSchema); export const Round = model('Round', roundSchema); export const Application = model('Application', applicationSchema); export const Notification = model('Notification', notificationSchema);
