import React, { useEffect, useState } from 'react'; import { createRoot } from 'react-dom/client'; import './styles.css';
const API=import.meta.env.VITE_API_URL || 'http://localhost:5050/api';
const Icon=({children})=><span className="icon">{children}</span>;
function Login({onLogin}) { const [email,setEmail]=useState('parthak@college.edu'),[password,setPassword]=useState('Password123!'),[error,setError]=useState(''); const submit=async e=>{e.preventDefault();setError('');const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)return setError(d.message);localStorage.setItem('placesmart',JSON.stringify(d));onLogin(d)}; return <main className="login"><section><p className="eyebrow">PLACEMENT MANAGEMENT</p><h1>Your next great opportunity starts here.</h1><p>One focused place for campus drives, interview updates, and your placement journey.</p><div className="login-note">Demo credentials are prefilled. Use <b>admin@placesmart.edu</b> to view the placement-cell dashboard.</div></section><form onSubmit={submit}><div className="brand"><b>place</b><i>smart</i></div><h2>Welcome back</h2><p className="muted">Sign in to your placement portal.</p><label>College email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{error&&<p className="error">{error}</p>}<button>Sign in <span>→</span></button></form></main> }
const navStudent=['Overview','Placement drives','My applications','Interviews','Notifications','My profile']; const navAdmin=['Overview','Students','Companies','Placement drives','Applications','Interview rounds','Reports','Notifications'];
function Sidebar({admin,tab,setTab,logout}){let nav=admin?navAdmin:navStudent;return <aside><div className="brand"><b>place</b><i>smart</i></div><p className="side-label">WORKSPACE</p>{nav.map((n,i)=><button key={n} className={`nav ${tab===n?'active':''}`} onClick={()=>setTab(n)}><Icon>{['⌂','▦','◫','◷','♧','◎','◉','♢'][i]}</Icon>{n}</button>)}<div className="side-bottom"><button className="nav" onClick={logout}><Icon>↪</Icon>Sign out</button></div></aside>}
function Stat({label,value,sub,tone}){return <article className={`stat ${tone||''}`}><p>{label}</p><h2>{value}</h2><small>{sub}</small></article>}
function StudentDashboard({token,user,tab}) {
  const [drives,setDrives]=useState([]),[apps,setApps]=useState([]),[notifications,setNotifications]=useState([]),[notice,setNotice]=useState('');
  const headers={Authorization:`Bearer ${token}`};
  useEffect(()=>{Promise.all([fetch(`${API}/placement-drives`,{headers}),fetch(`${API}/students/applications`,{headers}),fetch(`${API}/notifications`,{headers})]).then(async rs=>Promise.all(rs.map(r=>r.json()))).then(([d,a,n])=>{setDrives(d);setApps(a);setNotifications(n)});},[]);
  const apply=async id=>{let r=await fetch(`${API}/placement-drives/${id}/eligibility`,{headers}),e=await r.json();if(!e.eligible)return setNotice(e.reasons.join(' '));r=await fetch(`${API}/applications`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({driveId:id})});let d=await r.json();setNotice(r.ok?'Application submitted — it is now awaiting review.':d.message);if(r.ok)setApps([...apps,d]);};
  const selected=apps.filter(a=>a.status==='SELECTED').length;
  const pageHeader=(eyebrow,title,description)=><header><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{description}</p></div><button className="bell">♧<em>{notifications.filter(n=>!n.read).length}</em></button></header>;
  const driveList=<section className="panel drives"><div className="panel-title"><div><h2>Available placement drives</h2><p>Explore companies visiting your campus.</p></div></div>{drives.length?drives.map(d=><article className="drive" key={d._id}><div className="logo">{d.company?.name?.slice(0,1)}</div><div className="drive-info"><h3>{d.company?.name}</h3><p>{d.jobTitle} <b>·</b> {d.location}</p><div><span className="chip blue">₹ {d.packageLpa} LPA</span><span className="chip">Deadline {new Date(d.applicationDeadline).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div></div><button onClick={()=>apply(d._id)}>Apply now</button></article>):<div className="empty">There are no placement drives available right now.</div>}</section>;
  const applicationsList=<section className="panel drives"><div className="panel-title"><div><h2>My applications</h2><p>Every company you have applied to and its latest status.</p></div></div>{apps.length?apps.map(a=><article className="drive" key={a._id}><div className="logo">{a.drive?.company?.name?.slice(0,1)||'P'}</div><div className="drive-info"><h3>{a.drive?.company?.name||'Placement drive'}</h3><p>{a.drive?.jobTitle||'Job position'} <b>·</b> {a.currentStage||'Application submitted'}</p><div><span className="chip blue">{a.status.replace('_',' ')}</span>{a.rejectionReason&&<span className="chip">{a.rejectionReason}</span>}</div></div></article>):<div className="empty">You have not applied to any placement drives yet.</div>}</section>;
  const interviewApps=apps.filter(a=>a.status==='SHORTLISTED'||a.roundResults?.some(result=>['SCHEDULED','ATTENDED','SHORTLISTED'].includes(result.status)));
  const interviews=<section className="panel drives"><div className="panel-title"><div><h2>Upcoming interviews</h2><p>Your scheduled technical rounds and interviews.</p></div></div>{interviewApps.length?interviewApps.map(a=>{const round=a.roundResults?.find(result=>['SCHEDULED','ATTENDED','SHORTLISTED'].includes(result.status))?.round;return <article className="drive" key={a._id}><div className="logo">{a.drive?.company?.name?.slice(0,1)||'I'}</div><div className="drive-info"><h3>{a.drive?.company?.name||'Placement interview'}</h3><p>{round?.name||a.currentStage||'Interview details will be shared shortly'}</p><div><span className="chip blue">{round?.date?new Date(round.date).toLocaleDateString():a.status.replace('_',' ')}</span>{round?.location&&<span className="chip">{round.location}</span>}</div></div></article>}):<div className="empty">No interviews are scheduled at the moment.</div>}</section>;
  const notificationList=<section className="panel drives"><div className="panel-title"><div><h2>Notifications</h2><p>Placement updates, results, and deadlines.</p></div></div>{notifications.length?notifications.map(n=><article className="drive" key={n._id}><div className="logo">✦</div><div className="drive-info"><h3>{n.title}</h3><p>{n.body}</p><div><span className="chip">{new Date(n.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div></div></article>):<div className="empty">You have no notifications right now.</div>}</section>;
  const profile=<section className="panel drives"><div className="panel-title"><div><h2>My profile</h2><p>Your currently signed-in placement account.</p></div></div><article className="drive"><div className="logo">{user.name.slice(0,1)}</div><div className="drive-info"><h3>{user.name}</h3><p>{user.email||'College email unavailable'}</p><div><span className="chip blue">{user.role}</span></div></div></article></section>;
  if(tab==='Placement drives') return <>{pageHeader('PLACEMENT DRIVES','Find your next opportunity','Browse current companies and apply to roles that fit your profile.')}{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{driveList}</>;
  if(tab==='My applications') return <>{pageHeader('MY APPLICATIONS','Your applications','Follow each application from submission through the final result.')}{applicationsList}</>;
  if(tab==='Interviews') return <>{pageHeader('INTERVIEWS','Interview schedule','Stay prepared for your upcoming placement rounds.')}{interviews}</>;
  if(tab==='Notifications') return <>{pageHeader('NOTIFICATIONS','Your updates','The latest activity from the placement cell and companies.')}{notificationList}</>;
  if(tab==='My profile') return <>{pageHeader('MY PROFILE','Profile details','Review the account connected to your placement journey.')}{profile}</>;
  return <>{pageHeader('STUDENT DASHBOARD',<>Welcome back, {user.name.split(' ')[0]} <span>✦</span></>,`Here’s a clear view of where you are in your placement journey.`)}{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<section className="stats"><Stat label="OPEN OPPORTUNITIES" value={drives.length} sub="Matching your profile"/><Stat label="MY APPLICATIONS" value={apps.length} sub="Across active drives" tone="violet"/><Stat label="INTERVIEWS" value={interviewApps.length} sub="Scheduled or upcoming" tone="gold"/><Stat label="SELECTED" value={selected} sub={selected?'Congratulations!':'Keep going — you’re close'} tone="green"/></section><div className="content-grid">{driveList}<section className="panel journey"><div className="panel-title"><div><h2>Your journey</h2><p>Track progress across all applications.</p></div></div>{apps.length?<>{['Applied','Admin review','Technical round','Final result'].map((x,i)=><div className={`step ${i<2?'done':''}`} key={x}><span>{i<2?'✓':i+1}</span><div><b>{x}</b><small>{i===0?'Application submitted':i===1?'Awaiting shortlist decision':'Pending'}</small></div></div>)}</>:<div className="empty">Apply to an eligible drive to start your journey.</div>}</section></div></>;
}
function AdminDashboard({token}) { const [data,setData]=useState(null);useEffect(()=>fetch(`${API}/admin/dashboard`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(setData),[]);if(!data)return <p>Loading dashboard…</p>;return <><header><div><p className="eyebrow">PLACEMENT CELL</p><h1>Placement command center</h1><p className="muted">Monitor activity, manage drives, and keep every candidate moving.</p></div><button className="primary">+ Create drive</button></header><section className="stats"><Stat label="TOTAL STUDENTS" value={data.students} sub="Active student profiles"/><Stat label="COMPANIES" value={data.companies} sub="Campus recruiting partners" tone="violet"/><Stat label="ACTIVE DRIVES" value={data.activeDrives} sub="Open for applications" tone="gold"/><Stat label="TOTAL APPLICATIONS" value={data.applications} sub={`${data.selected} selected · ${data.rejected} rejected`} tone="green"/></section><section className="panel admin-panel"><div className="panel-title"><div><h2>Placement activity</h2><p>Current funnel across all active campus drives.</p></div><button className="link">View reports →</button></div><div className="funnel"><div><b>{data.applications}</b><span>Applications</span></div><div><b>{Math.max(data.applications-data.rejected,0)}</b><span>Under review</span></div><div><b>{data.selected}</b><span>Selected</span></div></div><div className="notice-box"><span>✦</span><div><b>Next action</b><p>Review newly received applications and publish upcoming round schedules.</p></div><button>Review applications</button></div></section></>}
function App(){const [session,setSession]=useState(()=>JSON.parse(localStorage.getItem('placesmart')||'null'));const [tab,setTab]=useState('Overview');if(!session)return <Login onLogin={setSession}/>;let admin=session.user.role==='ADMIN';return <div className="shell"><Sidebar admin={admin} tab={tab} setTab={setTab} logout={()=>{localStorage.removeItem('placesmart');setSession(null)}}/><main className="workspace">{admin?<AdminDashboard token={session.token}/>:<StudentDashboard token={session.token} user={session.user} tab={tab}/>}</main></div>}; createRoot(document.getElementById('root')).render(<App/>);
