import 'dotenv/config'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import User from './models/User.js'; import Student from './models/Student.js'; import Company from './models/Company.js'; import PlacementDrive from './models/PlacementDrive.js'; import Application from './models/Application.js'; import InterviewRound from './models/InterviewRound.js'; import Notification from './models/Notification.js';
if(!process.env.MONGO_URI){console.error('Set MONGO_URI in server/.env');process.exit(1)}
await mongoose.connect(process.env.MONGO_URI); await Promise.all([User.deleteMany({}),Student.deleteMany({}),Company.deleteMany({}),PlacementDrive.deleteMany({}),Application.deleteMany({}),InterviewRound.deleteMany({}),Notification.deleteMany({})]);
await User.create({name:'Placement Cell Administrator',email:'admin@placesmart.edu',password:await bcrypt.hash('Password123!',10),role:'ADMIN'});
const students=await Student.create([{name:'Aarav Sharma',email:'aarav.sharma@college.edu',registrationNumber:'PS2022001',branch:'Computer Science',cgpa:8.7,graduationYear:2026,phone:'9876543210',skills:['React','Node.js','MongoDB']},{name:'Diya Patel',email:'diya.patel@college.edu',registrationNumber:'PS2022002',branch:'Information Technology',cgpa:9.1,graduationYear:2026,phone:'9876543211',skills:['Java','SQL','Spring Boot']},{name:'Rohan Mehta',email:'rohan.mehta@college.edu',registrationNumber:'PS2022003',branch:'Electronics',cgpa:7.9,graduationYear:2026,phone:'9876543212',skills:['Python','C++','IoT']},{name:'Meera Nair',email:'meera.nair@college.edu',registrationNumber:'PS2022004',branch:'Computer Science',cgpa:8.3,graduationYear:2026,phone:'9876543213',skills:['Figma','JavaScript','UI Design']}]);
const companies=await Company.create([{name:'Infosys',industry:'Information Technology',description:'Global digital services and consulting company.',location:'Bengaluru',website:'https://www.infosys.com',recruiterName:'Anita Rao',recruiterEmail:'anita.rao@infosys.com',recruiterPhone:'9000000001'},{name:'Deloitte',industry:'Consulting',description:'Professional services and technology consulting.',location:'Hyderabad',website:'https://www.deloitte.com',recruiterName:'Karan Shah',recruiterEmail:'karan.shah@deloitte.com',recruiterPhone:'9000000002'},{name:'Zoho',industry:'Software',description:'Cloud software company.',location:'Chennai',website:'https://www.zoho.com',recruiterName:'Priya Iyer',recruiterEmail:'priya.iyer@zoho.com',recruiterPhone:'9000000003'}]);
const drives=await PlacementDrive.create([{company:companies[0]._id,jobTitle:'Systems Engineer',description:'Build and support enterprise software.',location:'Bengaluru',workMode:'Hybrid',package:'₹7.2 LPA',applicationDeadline:new Date('2026-09-15'),minimumCgpa:7,allowedBranches:['Computer Science','Information Technology'],requiredSkills:['Java','SQL'],status:'ACTIVE'},{company:companies[1]._id,jobTitle:'Technology Analyst',description:'Technology consulting graduate role.',location:'Hyderabad',workMode:'On-site',package:'₹9 LPA',applicationDeadline:new Date('2026-09-20'),minimumCgpa:7.5,allowedBranches:['Computer Science','Information Technology','Electronics'],requiredSkills:['Python','Communication'],status:'ACTIVE'},{company:companies[2]._id,jobTitle:'Software Developer',description:'Product engineering role.',location:'Chennai',workMode:'On-site',package:'₹8 LPA',applicationDeadline:new Date('2026-09-10'),minimumCgpa:8,allowedBranches:['Computer Science'],requiredSkills:['JavaScript','Java'],status:'ACTIVE'}]);
await Application.create([{student:students[0]._id,company:companies[0]._id,placementDrive:drives[0]._id,status:'SHORTLISTED',currentStage:'Technical Interview'},{student:students[1]._id,company:companies[1]._id,placementDrive:drives[1]._id,status:'UNDER REVIEW',currentStage:'Application Review'},{student:students[2]._id,company:companies[1]._id,placementDrive:drives[1]._id,status:'PENDING',currentStage:'Application'},{student:students[3]._id,company:companies[2]._id,placementDrive:drives[2]._id,status:'SELECTED',currentStage:'Offer'}]);
await InterviewRound.create([{company:companies[0]._id,placementDrive:drives[0]._id,roundName:'Technical Discussion',roundType:'Technical',date:new Date('2026-09-18'),time:'10:00 AM',location:'Seminar Hall A',description:'Technical interview for shortlisted candidates.'},{company:companies[1]._id,placementDrive:drives[1]._id,roundName:'Aptitude Assessment',roundType:'Aptitude',date:new Date('2026-09-22'),time:'02:00 PM',location:'Computer Lab 2',description:'Online aptitude assessment.'}]);
await Notification.create([{title:'Placement season is open',message:'Review active opportunities and keep your profile up to date.',targetAudience:'ALL_STUDENTS'},{title:'Interview scheduled',message:'Technical round for Infosys is scheduled on 18 September.',targetAudience:'DRIVE_STUDENTS',placementDrive:drives[0]._id}]);
console.log('Seed complete. Admin: admin@placesmart.edu / Password123!');await mongoose.disconnect();
